/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docs: [
    {
      type: "category",
      label: "Overview",
      link: {
        type: "doc",
        id: "intro",
      },
      collapsed: false,
      items: [],
    },
    {
      type: "category",
      label: "Quickstart",
      link: {
        type: "generated-index",
      },
      collapsed: false,
      items: [
        "quickstart/with-cli",
        "quickstart/with-http",
        "quickstart/with-go",
        "quickstart/with-java",
        "quickstart/with-typescript",
      ],
    },
    {
      type: "category",
      label: "Core Concepts",
      link: {
        type: "doc",
        id: "core-concepts/concepts",
      },
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Data Models",
          link: {
            type: "doc",
            id: "core-concepts/datamodels/overview",
          },
          collapsed: false,
          items: ["core-concepts/datamodels/schema"],
        },
        "core-concepts/filtering/filter",
        "core-concepts/change-events/introduction",
      ],
    },
    {
      type: "category",
      label: "Guides",
      link: {
        type: "generated-index",
      },
      collapsed: false,
      items: [
        "guides/rest-webapp-go",
        "guides/rest-webapp-java",
        "guides/rest-webapp-typescript",
      ],
    },
    {
      type: "category",
      label: "Client Libraries",
      link: {
        type: "generated-index",
      },
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Client Library: Java",
          link: {
            type: "generated-index",
          },
          items: [
            "client-libraries/java/overview",
            "client-libraries/java/sync-client",
            "client-libraries/java/async-client",
            "client-libraries/java/datamodel-java",
          ],
        },
        {
          type: "category",
          label: "Client Library: Go",
          link: {
            type: "generated-index",
          },
          items: [
            "client-libraries/go/overview",
            "client-libraries/go/go",
            "client-libraries/go/datamodel-go",
          ],
        },
        {
          type: "category",
          label: "Client Library: Typescript",
          link: {
            type: "generated-index",
          },
          items: [
            "client-libraries/typescript/overview",
            "client-libraries/typescript/typescript",
            "client-libraries/typescript/datamodel-typescript",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Command Line Interface",
      link: {
        type: "doc",
        id: "cli/overview",
      },
      collapsed: false,
      items: [
        "cli/working-locally",
        {
          type: "category",
          label: "Reference",
          items: [
            "cli/reference/alter-collection",
            "cli/reference/completion",
            "cli/reference/create-collection",
            "cli/reference/create-database",
            "cli/reference/delete",
            "cli/reference/describe-collection",
            "cli/reference/describe-database",
            "cli/reference/drop-collection",
            "cli/reference/drop-database",
            "cli/reference/generate-sample-schema",
            "cli/reference/insert",
            "cli/reference/list-collections",
            "cli/reference/list-databases",
            "cli/reference/local-down",
            "cli/reference/local-logs",
            "cli/reference/local-up",
            "cli/reference/ping",
            "cli/reference/read",
            "cli/reference/replace",
            "cli/reference/transact",
            "cli/reference/update",
            "cli/reference/version",
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
