/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docs: [
    'overview',
    {
      type: 'category',
      label: 'Quickstart',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
          'quickstart/quickstart-cli',
          'quickstart/quickstart-go',
          'quickstart/quickstart-java',
      ],
    },
    {
      type: 'category',
      label: 'Data Models',
      link: {
        type: 'generated-index',
      },
      items: [
        'data-models/overview',
        'data-models/schema',
        'data-models/data-types',
        'data-models/examples',
      ]
    }
  ]
};

module.exports = sidebars;
